# Load rbenv
if [ -x "$(command -v rbenv)" ]; then
  eval "$(rbenv init -)"
  export RUBY_CONFIGURE_OPTS=--with-readline-dir=`brew --prefix readline`
fi

# Load Nodenv
if [ -x "$(command -v nodenv)" ]; then
  eval "$(nodenv init -)"
fi
