# Load rvm
if [ -x "$(command -v rvm)" ]; then
  source "$HOME/.rvm/scripts/rvm"
  export RUBY_CONFIGURE_OPTS=--with-readline-dir=`brew --prefix readline`
fi

# Load rbenv
if [ -x "$(command -v rbenv)" ]; then
  eval "$(rbenv init -)"
  export RUBY_CONFIGURE_OPTS=--with-readline-dir=`brew --prefix readline`
fi

# Load Nodenv
if [ -x "$(command -v nodenv)" ]; then
  eval "$(nodenv init -)"
fi

# Load kiex
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

# Load pyenv
if [ -x "$(command -v pyenv)" ]; then
  eval "$(pyenv init -)"
fi
