# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Homebrew
source ~/.brewrc

ZSH_THEME="lambda"

# User configuration
source $ZSH/oh-my-zsh.sh

# PATH for Homebrew
export PATH="$PATH:/usr/local/sbin"

# PATH for Postgres
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
export PATH="$PATH:/usr/local/opt/postgresql@9.4/bin"

# Aliases
source ~/.aliases

# added by travis gem
[ -f /Users/samneely/.travis/travis.sh ] && source /Users/samneely/.travis/travis.sh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
