# Path to your oh-my-zsh installation.
export ZSH=/Users/samneely/.oh-my-zsh

# Homebrew
~/.brewrc

ZSH_THEME="lambda"
plugins=(git ruby rails)

# User configuration
source $ZSH/oh-my-zsh.sh

# PATH for Homebrew
export PATH="$PATH:/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin"

# Aliases
source ~/.aliases
